### ISSUE TITLE
Web service cannot get info

### ISSUE THREAD

**Issue by LARGH** [ConroeSoluciones/CSReporter-API-Java#3]
Tengo un problema, resulta que al ejecutar consultas simples de CSReporter-API-Java (class com.csfacturacion.csreporter.impl.CSReporterIT), no puedo obtener informacion de facturas, estas son las entradas:

**Input:**
 - Credenciales CsReporter: 
"usuario": "RFC"
"password": "PWD"
 - Sat credenciales:
   - RFC empresa: RFC
   - contraseña SAT de la empresa: *******
 - Periodo de facturas recibidas: 
2015, 02, 01
2015, 03, 31

Se supone que este enlace es al que se conecta el **servicio**: 
_https://www.csfacturacion.com/webservices/csdescargasat/?method=ObtenerCfdisV2&cServicio=14&cRfcContrato=RFC&cpassContrato=PWD&tipoBusqueda=EXHAUSTIVA&complementos=-1&cConsulta=emitidas&cEstatus=vigentes&cRfcSearch=todos&cRfc=rfc&cPassword=password&cFchI=2018-10-01T00:00:00&cFchF=2018-10-01T23:59:59_

Y obtengo esta **respuesta**:
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $
        at com.google.gson.JsonParser.parse(JsonParser.java:65)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at com.csfacturacion.csreporter.impl.http.Response.getAsJson(Response.java:34)
        at com.csfacturacion.csreporter.impl.CSReporterImpl.consultar(CSReporterImpl.java:145)
        at com.csfacturacion.csreporter.impl.CSReporterIT.consultarAsync(CSReporterIT.java:108)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

Obtengo este **error**:
Error conectando a la base de datos.{"UUID":"","MENSAJE":"ERROR 102 El rfc que estas intentando consultar no tiene el servicio habilitado","CONTRATACION":"0","TRANSACCIONES":"0","IDCONTRATACION":""}

**Comment by landeber** [comment]
Hola LARGH, 

Comunicate con un asesor para permitir que tu empresa tenga acceso al servicio de descarga de CFDIs desde el SAT. La página es https://csfacturacion.com.

Saludos!
